### ISSUE TITLE
mcrun command line got invalid character @! error

### ISSUE THREAD

**Issue by juxiangwu** [Moddable-OpenSource/moddable#1098]
mcrun -d -m -p esp32
# xsc time.xsb
/home/iotservice/develop/moddable/modules/base/time/time.js:27: error: invalid character @!
### 1 error(s)
make: *** [/home/iotservice/develop/moddable/build/tmp/esp32/debug/helloworld/makefile:166: /home/iotservice/develop/moddable/build/tmp/esp32/debug/helloworld/files/time.xsb] Error 22

OS:Ubuntu22.04
ESP-IDF:4.4.3

**Comment by mkellner** [comment]
Hello.

`mcconfig` is used to build applications such as `helloworld`. See step 10 of the [Using the Moddable SDK with ESP32](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/esp32.md#installing-2) document.

`mcrun` is intended to be used with Mods. See the [Mods](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/mods.md) documentation for details.

**Comment by phoddie** [comment]
To expand on what @mkellner wrote, Mods are JavaScript-only.  The `time` module contains native code and so cannot be contained in a mod. Hosts can contain native code.

Mods are built, installed, and run using `mcrun`. Hosts are built, installed, and run using `mcconfiig`.

Based on the error building the `time` module, it looks like you are tried to build a host using `mcrun` instead of `mcconfig`.

I've made changes to `mcrun` to report a more helpful error message. That will be available later this week.
