### ISSUE TITLE
NRF52_SDK_PATH environment variable （Windows）

### ISSUE THREAD

**Issue by NW-Lab** [Moddable-OpenSource/moddable#1199]
hello,

Is nRF5_SDK_17.0.2_d674dde the correct environment variable for nRF52?
It is now written as nRF5_SDK_17_0_2_d674dde.

![image](https://github.com/Moddable-OpenSource/moddable/assets/8869009/2cd3c545-2fba-4be0-8ad8-d875b5a2ca27)

tahnk you,

**Comment by phoddie** [comment]
Thank you for the report.

It looks like there are some inconsistencies. The directory in the downloaded Nordic nRF52 SDK is named "nRF5_SDK_17.0.2_d674dde" not "nRF5_SDK_17_0_2_d674dde". The difference is one "." instead of "_".

The `NRF52_SDK_PATH` environment variable should be set to `nRF5_SDK_17.0.2_d674dde` (with the dot), of course.

The [macOS instructions](https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/devices/nrf52.md#mac-instructions) are correct. The Windows and Linux instructions are inconsistent. We'll recheck that and post an update.
