### ISSUE TITLE
not enough IDs!

### ISSUE THREAD

**Issue by Ethirajulu** [Moddable-OpenSource/moddable#195]
Hi Team, we are running into following error in our application.

`not enough IDs!`

We are not sure what this message denotes. This occurs during a loop. 

Our Analysis: The error is from the function fxNewNameX() from xsSymbol.c (Line: 390)

	index = the->keyIndex;
	if (index == the->keyCount)
		mxUnknownError("not enough IDs");

Could you please give us details on what this error is about.

And also could you please let us know how to check the application build size.

**Comment by phoddie** [comment]
The `not enough IDs` message indicates that you have exhausted the space reserved for JavaScript symbols defined at runtime. Space for symbols defined at build time is automatically reserved in flash memory, so it takes no memory. You can see the runtime symbol use in the Instrumentation in panel in xsbug, so you can track down where it is happening.

It might mean you are creating symbols with code like this:

```
object["foo"] = 12;
```

Instead of this:

```
object.foo = 12;
```

It also can happen if you are parsing JSON objects which contain many new symbols. If you know the symbols your JSON contains, you can simply predeclare them in your script to have the put into flash during the build:

```
// define symbols expected in JSON
let time_stamp, id, hash_value, temperature_c, temperature_f;
```


Of course, you cannjust to increase the number of symbols. Needless to say, that isn't sustainable as it also increases the amount of RAM required for symbols. To do that, in your manifest:

	"creation": {
	...
		"keys": {
			"available": 128,
		}
	}
