### ISSUE TITLE
Allow setting a timeout when setting up an I2C connection

### ISSUE THREAD

**Issue by k45514n** [Moddable-OpenSource/moddable#246]
Allow the user to pass in a `timeout` parameter that will account for clock stretching, slow reads, etc from I2C devices. Spawned from #237

**Comment by phoddie** [comment]
@nodebotanist - In #237 you noted that you were going to try implementing a solution here. Any update?

**Comment by k45514n** [comment]
Sorry, had to take a break from everything for a bit. Started work back up again.

**Comment by andycarle** [comment]
This was implemented for ESP8266 and ESP32 back in 8e39234b7cf047b0475d1e9a74548551ced142b4. Since it has been implemented and this issue has been idle for some time, I'm going to go ahead and close this out.

Please feel free to re-open this or start up a new issue if there are any problems with the timeout implementation!

&nbsp;- Andy
