### ISSUE TITLE
defineProperties on Promise.prototype gives "invalid descriptor!"

### ISSUE THREAD

**Issue by dckc** [Moddable-OpenSource/moddable#255]
still struggling to port `test-marshall.js` from SwingSet; now I get:
```
agoric/SwingSet/node_modules/@agoric/eventual-send/dist/eventual-send.esm.js (57) # Break: (host): invalid descriptor!
```
https://github.com/Agoric/eventual-send/blob/master/src/index.js#L57

I reduced it to the following. If I run it in node, I get `defined: getX` as expected. In xs (without the `trace` definition, and with `export default function main`) I get `main.js (4) # Break: (host): invalid descriptor!`.

Perhaps that's by design? Perhaps I should be using `preload` or Compartments differently to do this sort of thing?

```js
function trace(s) {
  console.log(s);
}

function main() {
  trace('in main\n');

  Object.defineProperties(
    Promise.prototype,
    Object.getOwnPropertyDescriptors({
      getX(key) {
        return 2;
      },
    }),
  );

  trace(`defined: ${String(Object.keys(Promise.prototype))}\n`);
}

main();
```

cc @erights @michaelfig

**Comment by phoddie** [comment]
If I understand correctly what is happening, `Object.defineProperties` is failing when applied `Promise.prototype` because `Promise.prototype` is frozen. 

If you want to patch `Promise.prototype` you need to run before it is frozen, during preload time. In SES terminology, that means you are _vetted customization code_. To do that in your example, set the main module to be preloaded in the manifest, then reorganize the code:

```js
Object.defineProperties(
	Promise.prototype,
	Object.getOwnPropertyDescriptors({
		getX(key) {
			return 2;
		},
	}),
);

function main() {
  trace('in main\n');

  trace(`defined: ${String(Object.keys(Promise.prototype))}\n`);
}

export default function() {
	main();
}
```

The module body is executed during preload, before `Promise.prototype` is frozen. The function exported as the default is executed at runtime and outputs `defined: getX`.

**Comment by dckc** [comment]
ok, so this is as-designed. thanks.

I think I tried to do the preload thing, but I'll try again.

**Comment by dckc** [comment]
ok... so that particular program works fine, but I still can't figure out how to get preloading working in a larger program with multiple modules. Part of the problem is that the diagnostics for preloading seem to be more primitive.

Got any clues on what this means?

```
$ mcconfig -d -m -p lin
# xsc main.xsb
# xsl modules
# cc mc.xs.c
/home/connolly/projects/moddable/build/tmp/lin/debug/mc/test-kernel-xs/mc.xs.c:7594:123: error: ‘OOPS’ undeclared here (not in a function)
 txSlot*)&gxHeap[2113], {.ID = XS_NO_ID, .flag = 0x8f, .kind = XS_CALLBACK_X_KIND}, .value = { .callback = { OOPS, NULL } }},                                                                     
```

**Comment by dckc** [comment]
Oh... the code I'm trying to preload includes `new WeakMap()`, which I see is among the "objects which cannot be stored in flash memory".

**Comment by dckc** [comment]
I delayed creation of the WeakMap, but I can't figure out this OOPS stuff.

I reduced it to this gist; if you can take a look, I'd sure appreciate it.

https://gist.github.com/dckc/685b595f5c41f4ec2de47cd2d1ab3a74

**Comment by phoddie** [comment]
The issue is that bound functions were not being handled by preload correctly. That has been fixed. The change is in `xsl` (the linker) so it is necessary to rebuild tools.

Here's a small example, excerpted from your Gist, that shows the problem if executed at preload time:

```js
const baseResolve = Promise.resolve.bind(Promise);

Object.defineProperties(
	Promise,
	Object.getOwnPropertyDescriptors({
	  resolve(value) {
			return baseResolve(value);
	  },
	}
));
```

FWIW - This new report about the build error is only related to the original issue in that both involve preload. It is different enough that it should probably have been a separate report.

**Comment by dckc** [comment]
> ... bound functions were not being handled by preload correctly. That has been fixed.

Thanks!

> FWIW - This new report about the build error is only related to the original issue in that both involve preload. It is different enough that it should probably have been a separate report.

OK... I suppose that applies to my next problem, which is `dead strip!` ... more on that when I have it isolated a bit...
