### ISSUE TITLE
docs for keys.available? (not enough IDs!)

### ISSUE THREAD

**Issue by dckc** [Moddable-OpenSource/moddable#272]
I got `# Exception: Object.prototype.hasOwnProperty: not enough IDs!` while working on Agoric/Swingset stuff. Based on grepping the xs source code, I figured out that this makes the symptoms go away:

```
  "creation": {
    "keys": {
      "available": 256
```

This `keys.available` stuff is mentioned in https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/tools/manifest.md#creation but without explanation. The default in the examples seems to be 32. 32 what? What are the units? And in what circumstances is this resource consumed?

Likewise docs for `keyCount` in
https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/xs/XS%20in%20C.md#machine-allocation . Please elaborate a bit.

**Comment by phoddie** [comment]
The engine allocates storage for dynamically created symbols (for example, property names) when the virtual machine is created. These are symbols beyond what is defined by the JavaScript language and used in any preloaded modules. The storage allocated is sufficient to hold `creation.keys.available` dynamically created symbols.

Because it is rare to create symbols at runtime on embedded systems thanks to preload, the default values in our manifests are small. This helps to conserve RAM. You may increase that value in your project manifest. The total number of symbols in a virtual machine -- defined in ECMA-262, used in preloaded modules, and created at runtime -- cannot exceed 32767.
