### ISSUE TITLE
websocket send() can't write messages > kTxBufferSize (1024 bytes)

### ISSUE THREAD

**Issue by dckc** [Moddable-OpenSource/moddable#313]
websocket.js passes up to 64k of data to one call to socket.send(), but kTxBufferSize is only 1024 bytes, so I get:

```
modules/network/socket/lin/modSocket.c (761) # Exception: (host): can't write all data!
```

The docs say to use `socket.send()` with no args to get the amount of data that can be sent.

I guess I can bump up `kTxBufferSize` but websocket.js should break the data into pieces, no?

**Comment by phoddie** [comment]
Having a limit on the output is by design as it models the reality of limited TCP buffer space on microcontrollers. The WebSockets implementation could buffer, only helps a handful of cases as it still uses additional RAM. A scalable solution would involve a streaming data callback so that the data can be synthesized or loaded into RAM in parts, as write buffer space becomes available. That's a significant undertaking, perhaps more appropriate for the TC53 network protocols effort.
