### ISSUE TITLE
pubnub example broken

### ISSUE THREAD

**Issue by bartmichu** [Moddable-OpenSource/moddable#329]
Pubnub example compiles and uploads fine but then fails with:

```
Wi-Fi connected to "redacted"
IP address 10.0.0.17
Generating time-based UUID.
Subscribing...
/home/redacted/redacted/moddable/modules/network/socket/lwip/modSocket.c (705) # Break: (host): unsupported type for write!
```
I'm using esp8266 board.

**Comment by lprader** [comment]
Thanks for the report. I've committed a fix that will be included in our next open source update. 

If you want to try it out before then, replace `$MODDABLE/modules/network/services/pubnub/pubnub.js` with [this](https://github.com/Moddable-OpenSource/moddable/files/4150542/pubnub.txt). Note that you'll have to change the file extension to .js (because GitHub apparently doesn't allow attaching .js files here).

**Comment by bartmichu** [comment]
That was quick, thank you - I can confirm that it works fine for me with your fix.

**Comment by andycarle** [comment]
This fix is now live in the open source repo.
