### ISSUE TITLE
monotype-fonts examples

### ISSUE THREAD

**Issue by wilberforce** [Moddable-OpenSource/moddable#363]
Hi, this blog post mentions the spark engine:

https://www.moddable.com/monotype-fonts.php

I can't locate any examples?

These examples are for bitmap fonts:
https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/piu/piu.md#font
https://github.com/Moddable-OpenSource/moddable/blob/public/documentation/commodetto/poco.md#text

Thanks!

**Comment by phoddie** [comment]
True. The Spark engine is proprietary software. As a result, we are only able to provide the Moddable SDK support for that to people  and organizations that have a license to Spark from Monotype.

FWIW - scripts use the Monotype engine more-or-less exactly as they do with bitmap fonts. For example, Piu styles still use the CSS based format.  They just happen to be able to get a lot more sizes. The resources data, of course, is a TrueType (OpenType) font rather than a BMF. Here's an example of a Piu style using one of the Monotype fonts optimized for embedded use with Spark:

```
const style = new Style({ font:"light 64px Frutiger", color:["white", "black"] });
```

There are a few new APIs to support working with glyph outlines directly, something that's obviously not possible with bitmap fonts.
