### ISSUE TITLE
Can I install the Moddable SDK on Windows 7 (SP2), without Visual Studio? 

### ISSUE THREAD

**Issue by astroanax** [Moddable-OpenSource/moddable#425]
I don't want to install Visual Studio on my computer. I do have Visual Studio Code, although it might not help. I see that Visual Studio isn't needed for other OSes, so was wondering if this was possible?

**Comment by andycarle** [comment]
You will need Visual Studio to build the Moddable SDK. The build process uses the compiler and other tools that come with Visual Studio to build the Windows platform-specific executables in the Moddable SDK tools. XCode fills the same role in our macOS build. 

We also do not support Windows 7, because it is [End-of-Life](https://support.microsoft.com/en-us/help/4057281/windows-7-support-ended-on-january-14-2020).
