### ISSUE TITLE
contents of Map don't survive 2nd snapshot / restore

### ISSUE THREAD

**Issue by dckc** [Moddable-OpenSource/moddable#488]
**Steps to Reproduce**

in `maptest.js`:
```js
const progress = [];
const mapTest = new Map();

function proceed() {
  progress.push('moar!');
  mapTest.set(progress.length, 'thing');
  print(progress.length);
  print(progress);
  print(mapTest.size);
  print([...mapTest.entries()]);
}

globalThis.proceed = proceed;

proceed();
```

in `mapcont.js`:
```
proceed();
```

Then invoke...

```
$ xsnap -m maptest.js -w s1.xsnap
1
moar!
1
1,thing
$ xsnap -m mapcont.js -r s1.xsnap -w s2.xsnap
2
moar!,moar!
2
1,thing,2,thing
$ xsnap -m mapcont.js -r s2.xsnap -w s3.xsnap
3
moar!,moar!,moar!
1
3,thing
```

**Expected behavior**

as above but for the last 2 lines:

```
3
1,thing,2,thing,3,thing
```

**Build environment:** Linux
**Target device:** xsnap
sdk version 748fda9359ea20ec0b4ff224f2cf077f47b6e507
xsnap version e8199b1012981d627a77235bb6737f9deef07103

cc @warner @erights @phoddie

**Comment by phoddie** [comment]
There is a bug in the loading of Maps. The fix is small, so I'll post it here ahead of us updating this repository. Replace these lines:

https://github.com/Moddable-OpenSource/moddable/blob/748fda9359ea20ec0b4ff224f2cf077f47b6e507/xs/sources/xsSnapshot.c#L763-L765

With:

```js
slot = the->firstHeap + 1;
```

The test isn't quite right though. The second step loads `mapcont.js` so the third step does nothing as that module is already loaded. mapcont.js is already loaded so nothing happens.

```
$ xsnap -m maptest.js -w s1.xsnap
1
moar!
1
1,thing
$ xsnap -m mapcont.js -r s1.xsnap -w s2.xsnap
2
moar!,moar!
2
1,thing,2,thing
$ xsnap -m mapcont.js -r s2.xsnap -w s3.xsnap
```

You need a separate module, such as `mapcont2.js`:

```
proceed();
```

Then the output is as you expect:

```
$ xsnap -m mapcont2.js -r s2.xsnap -w s3.xsnap
3
moar!,moar!,moar!
3
1,thing,2,thing,3,thing
```

**Comment by dckc** [comment]
confirmed. thanks!

(committed locally / temporarily as fb0141f3)
