### ISSUE TITLE
Out of memory warning during build/simulation? 

### ISSUE THREAD

**Issue by techninja** [Moddable-OpenSource/moddable#56]
Making great progress with the game I'm making with my son, but suddenly adding a sprite sheet to the manifest results in the build breaking in strange ways. Totally stopping the project in its tracks.

https://github.com/makerzeph/squishybabs/pull/1

```
# png2bmp faces-color.bmp faces-alpha.bmp
# mcrez resources
# cc mc.resources.c (slots in flash)
# ld main.bin
/home/techninja/esp/toolchain/Linux/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.5/../../../../xtensa-lx106-elf/bin/ld: /home/techninja/web/moddable/build/tmp/esp/release/src/main.elf section `.irom0.text' will not fit in region `irom0_0_seg'
collect2: error: ld returned 1 exit status
/home/techninja/web/moddable/build/tmp/esp/release/src/makefile:525: recipe for target '/home/techninja/web/moddable/build/bin/esp/release/src/main.bin' failed
```

I tried cropping the image in half and it built, though there were other issues and this doesn't solve the implementation problem. I suppose my questions are as follows:

1. Are there image resource size limits for images?
2. Should there be clearer build failures for resource exhaustion?
3. Is there any way I can keep working on this project using sprites without moving to some other drawing method (image compression, custom color indexed images, vector)?

**Comment by phoddie** [comment]
Yes, that warning indicates flash is full. Agreed that it isn't the most friendly message, but it is what GCC gives. It would be great to see a more friendly message there. Any ideas of hoot do that in the make file?

In your current source tree, it looks like everything fits with plenty of room (flash size is 863408 in my ESP8266 build) of your code). The ESP8266 has a hard 1 MB limit on how much flash can be memory mapped. Both code and images are included in that space. The images are there so that they can be rendered quickly directly from flash without ever being loaded in the (even more limited) RAM.

The SDK supports compression for 4-bit gray masks. They are compressed with a weighted RLE algorithm that is directly decoded. They can be drawn in any color. That's what the font uses, for example. If you adjust your graphics to use that, perhaps by having two images to get a pair of colors, it will be considerably smaller (and probably render faster too). We use masks like this a lot in our projects as a practical compromise.

Another solution is to use 8-bit RGB332 rendering. The SDK supports that on ESP8266 and Mac. You lose some color resolution, though for a game it probably isn't that important. In my build of your app it saves about 66 KB of ROM (because the graphics are stored in ROM at 8 bits per color pixel rather than 16). To try it, do this: `mcconfig -d -m -f rgb332 -p esp`

Side note, you can remove button.png and desktop.png from your manifest to save a little space.
