### ISSUE TITLE
custom font

### ISSUE THREAD

**Issue by mauroForlimpopoli** [Moddable-OpenSource/moddable#602]
I created a new font from a ttf file with "bitmap font generator" and it looks right.

This is the js code:
const dayLater = Style.template(Object.freeze({ font: "day24b", color: "orange", horizontal:"left", vertical:"middle"}));
this is the code of manifest:
	"resources":{
		"*-alpha": [
			"$(MODDABLE)/examples/assets/fonts/OpenSans-Regular-72",
			"$(MODDABLE)/examples/assets/fonts/day24b"
		],
		"*-image(100)": [
			"$(MODDABLE)/examples/assets/images/back-icon"			
		]
	},

These are the converted files
[day24b_0.zip](https://github.com/Moddable-OpenSource/moddable/files/6126610/day24b_0.zip)

But when running the compile shows this error:
C:\Users\fly3\projects\moddable\modules\piu\MC\piuMC.js (71) # Break: throw!

**Comment by mauroForlimpopoli** [comment]
Here where I use the font:
const setLabel = new Label(null, {
	 top: 120, bottom: 15, left: 30, right: 30,
	 style: new dayLater(),
	 state: 0,
	 string: "Start",
	 skin: butBackground,
	 active: true,
	 Behavior: LabelBehavior
});

**Comment by lprader** [comment]
When I download the font files, the png is named `day24b_0.png`. It should be `day24b.png` to match the name of the fnt file.

With that change, I'm able to use the font in a test application.

Also, for future reference, `xsbug` is a great tool :) Note that the code that throws the error is traced to the console and highlighted in the source code, and you can use the LOCALS pane on the left side of the window to figure out which texture is missing. That gives a good clue about what the problem is.

<img width="1552" alt="error" src="https://user-images.githubusercontent.com/3871375/110873429-94e20100-8286-11eb-9cb9-1c16a0a0267a.png">

**Comment by mauroForlimpopoli** [comment]
Thank you Lizzie. Your assistance about XSBUG debugger will be usefull for the future also.
