### ISSUE TITLE
ToNumber incorrectly accepts "INFINITY"

### ISSUE THREAD

**Issue by gibson042** [Moddable-OpenSource/moddable#885]
**Environment:** XS 11.6.0 32 4

**Description**
XS incorrectly converts a string like "INFINITY" into `Infinity` rather than `NaN`.

**Steps to Reproduce**
```js
const inputs = ["Infinity", "INFINITY", "infinity", "inFiNiTY"];
inputs.map(str => `Number("${str}") // => ${Number(str)}`).join("\n");
// =>
// Number("Infinity") // => Infinity
// Number("INFINITY") // => Infinity
// Number("infinity") // => NaN
// Number("inFiNiTY") // => NaN
```

**Expected behavior**
Only the "Infinity" capitalization should be given special treatment, with all other variants converted to `NaN` per [StringToNumber](https://tc39.es/ecma262/#sec-stringtonumber) parsing input against [_StringNumericLiteral_](https://tc39.es/ecma262/#prod-StringNumericLiteral).

**Actual behavior**
XS privileges both "Infinity" and "INFINITY".

**Comment by phoddie** [comment]
The bug appears to happen because the [`match` function](https://github.com/Moddable-OpenSource/moddable/blob/d7895e48268b2a347cac01348c920695d05ab9bf/xs/sources/xsdtoa.c#L2614-L2628) used [by `dtoa2`](https://github.com/Moddable-OpenSource/moddable/blob/d7895e48268b2a347cac01348c920695d05ab9bf/xs/sources/xsdtoa.c#L3728-L3740) is case insensitive.

The only other place `match` is used is to detect NaN. But there's no problem there because "NAN" evaluates to `NaN` anyway.

So, it looks like it would be enough to modify `match` to be case-sensitive.
