### ISSUE TITLE
Websocket windows issue

### ISSUE THREAD

**Issue by thobias90** [Moddable-OpenSource/moddable#912]
**Build environment:** Windows
**Target device:** Mcsim

**Description**
I have an application that runs with mcsim to simulate the real hardware. To exchange message between mcsim and application I am using websocket. Mcsim instantiate a client and connect to the server running on the application. This approach works for macOS system, but when trying to run on windows it is failing with the message:

- Break: (host): No Function

**Steps to Reproduce**
1. Create an application that instantiate a websocket server
2. On mcsim side instantiate the websocket client and tries to connect to the server

**Expected behavior**
The expected behavior is that mcsim client connect to app server, handshake and be able to exchange messages.

**Other information**
With different behavior between macOS and Windows I started to look at the modSocket.c implementation for Windows. 
I found that the function **createSocketWindow** was using always the same name for the attribute lpszClassName into the WNDCLASSEX structure. 
Accordingly to this [document](https://docs.microsoft.com/en-us/windows/win32/learnwin32/creating-a-window#:~:text=Class%20names%20are%20local%20to%20the%20current%20process%2C%20so%20the%20name%20only%20needs%20to%20be%20unique%20within%20the%20process.), it is expected unique class name per process. 
Since the simulator and application are running on the same process, the client and the server will execute the **createSocketWindow** registering two window with the same name and generating this error.

**Comment by phoddie** [comment]
Thank you for your report.

The "steps to reproduce" are insufficient to easily reproduce the problem. Among other things, they would appear to require creating a new simulator, for example. Please provide an example that reproduces the problem.

> Accordingly to this document, it is expected unique class name per process. Since the simulator and application are running on the same process, the client and the server will execute the createSocketWindow registering two window with the same name and generating this error

That doesn't appear to add-up. Even if there is a requirement for a unique class name for each process, the simulator and application are in the same process and so such a requirement would not be relevant.

> ...the client and the server will execute the createSocketWindow registering two window with the same name and generating this error

The error you note is generated by XS, not Windows. Any relationship between registering the Window Class and the error is not clear based on the information provided.

**Comment by thobias90** [comment]
I have created an example to reproduce the problem. 
It was created into moddable/examples and it's called myexample and it can be found [here](https://github.com/thobias90/moddable).

**About the app:**
- It is a websocket server running on port 80 and it is very similar to the websocket example.

**About the simulator:**
- It is extending the mcsim app and also is a websocket client very similar to the websocket example. The only thing is that the client will be started after one second to let the server runs before the client.

For accomplish that I have to add support into mcsim app for the websocket and timer modules. This changes can be seen [here](https://github.com/thobias90/moddable/commit/08f8fb3c74b478aa5fc99e32df03ccf7f68b2079).

**Expected behavior**
The client should connect to the server and send a message. 

**Actual behavior**
The app is breaking with the log message: **# Break: (host): no function**.

**Steps to reproduce**
On Windows machine build and run myexample [app](https://github.com/thobias90/moddable/tree/public/examples/myexample). When launched locate the simulator for myexample app that is stored into [myexample/simulator](https://github.com/thobias90/moddable/tree/public/examples/myexample/simulator).

**Debug Logs**
This image is printed from myexample app running on macOS System. This is the expected behavior.
![Captura de Tela 2022-06-06 às 12 18 54](https://user-images.githubusercontent.com/38568515/172205479-20460343-5243-49de-a158-295ab29bbad0.JPG)

This image below is printed from myexample app running on Windows System. This is the actual behavior.
![win-socket-break](https://user-images.githubusercontent.com/38568515/172206569-8037d8f9-36a5-40ca-8a75-58923521c4e9.PNG)

**Wireshark Logs**
The first one is from myexample app running on macOS System. It is possible to see the TCP connection and the websocket handshake.
![Captura de Tela 2022-06-06 às 14 22 34](https://user-images.githubusercontent.com/38568515/172213123-1179a7d2-cdfd-4bb0-a763-ade2b4c50476.JPG)

The second is from myexample app running on Windows System. It is possible to see the TCP connection, then the client send the HTTP packet to do the handshake, but the server does not answer.
![win-socket-wireshark](https://user-images.githubusercontent.com/38568515/172213149-a7ec8b89-0410-48f0-86f5-a2112827fc0b.PNG)

**Analysis:**
The problem happens on the server side when it switches the responsibility to the dedicated socket from the listener. When a client connection is received, the listener accepts the connection and creates a dedicated socket for the communication. Though the client connection is getting accepted over the listener, it is crashing when the socket has to take over the communication. 

Here we can see that the server is handling the initial connection on the listener and after that it creates a socket same as the client socket to have the dedicated communication. I guess it is creating conflict or problem when the new client also comes live on the same application.
![image](https://user-images.githubusercontent.com/38568515/172215981-fcd40f34-ddcb-49b6-9ea3-b3c592c0be7d.png)

The socket will register the Window using the function below. We have the scenario where the same process is registering more than one Window class with the same name **modSocketWindowClass**. And I guess that's where it is creating problems.
![Captura de Tela 2022-05-31 às 10 17 46 (1)](https://user-images.githubusercontent.com/38568515/172216586-0d4cc19a-000d-4407-921b-6d4047424551.JPG)

**Comment by phoddie** [comment]
Thank you for the example and additional details. That is helpful in understanding the issue and what you are trying to accomplish.

It is important to understand how the simulator works. It runs two completely separate copies of the Moddable SDK:

- One copy for the simulator itself. This is part of `mcsim`. It is built as part of the Moddable SDK tools.
- One cccopy for the project being run in the simulator. This is part of the project's executable. It is built each time the project is run using `mcconfig`.

The simulator and project each has a JavaScript virtual machine. Those are almost entirely unrelated. It is why modules included in a project are unavailable to the simulator, for example.

This isolation is important to maintaining the abstraction between  the simulator and the project. For example, they cannot observe each other or use JavaScript to access other's objects, data, and methods.

Having two separate copies of the Moddable SDK means that any modules used in both the simulator and project cannot have any global interactions. The way modules are implemented means that this is generally the case. However, in some cases the host (Windows here) maintains global state that crosses between the two copies. This is rare, but can lead to failures.

Perhaps this can be solved in a reliable way for the Windows socket implementation. But, I'm not sure how. And there could be other follow-on issues.

Fortunately, there is no need here to solve the problem. The simulator provides a mechanism to communicate between the project and simulator by passing objects (effectively JSON). This mechanism is quite a bit more efficient, is fully supported (because it is how all of the built-in simulators are implemented), and does not trigger this obscure Windows global state interaction with sockets using a window to receive events. Rather than building your own road for messages to travel between the project and simulator, it would be best to use the well established road provided by the simulator.
